name: Build Current

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod vendor

      - name: Build artifacts
        run: make VERSION=$(git rev-parse --short HEAD)
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: preflight binaries
          path: dist/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: dist/
          asset_name: preflight-$(git rev-parse --short HEAD)
          tag: ${{ github.ref }}
          overwrite: true